DROP DATABASE IF EXISTS orders;

CREATE DATABASE orders;
USE orders;

CREATE TABLE customerInfo (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  line1 VARCHAR(30) NOT NULL,
  line2 VARCHAR(10) NULL,
  city VARCHAR(20) NOT NULL,
  st VARCHAR(2) NOT NULL,
  zip VARCHAR(5) NOT NULL,
  ccNum VARCHAR(19) NOT NULL,
  expYear INT NOT NULL,
  expMonth INT NOT NULL,
  cvv INT NOT NULL,
  billZip INT NOT NULL,
  PRIMARY KEY (id)
);